# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
